-- ### SQL Queries
-- Instructions: rename the file cognome.sql
-- #### Part 1
-- 1. List all albums along with the artist name
<<<<<<< HEAD
-- 2. Find all tracks and their album names
=======
SELECT * FROM pippo;
-- 2. Find all tracks and their album names
SELECT t1.common_column, t2.common_column 
FROM table1 t1
JOIN table2 t2 ON t1.common_column = t2.common_column;
>>>>>>> a610b63 (Update SQL queries and add UML class diagram for electronic devices)
-- 3. List all tracks with their genre and media type
-- 4. Find the total number of tracks in each playlist
-- 5. List all customers along with their support representative's name
-- 6. Find the total amount spent by each customer
-- 7. List all invoices along with the customer's name and the total amount
-- 8. Find the most expensive track
-- 9. List all employees and their managers
-- 10. Find the total number of tracks in each genre
-- #### Part 2
-- 1. Find the total sales for each album
-- 2. List all customers who have never made a purchase
-- 3. Find the most popular genre by the number of tracks sold
-- 4. List all employees along with the number of customers they support
-- 5. Find the average invoice total for each customer
-- 6. List all tracks that are part of more than one playlist
-- 7. Find the total number of tracks sold for each media type
-- 8. List all albums that have tracks in more than one genre
-- 9. Find the total revenue generated by each genre
-- 10. List all customers along with the total number of invoices they have
-- #### Part 3
-- 1. Find the top 5 customers who have spent the most money
-- 2. List all tracks that have never been sold
-- 3. Find the employee who supports the most customers
-- 4. Find the total revenue generated by each artist
-- 5. List the top 3 genres by total sales revenue
-- 6. List all employees who do not have any direct reports
-- 7. Find the total number of tracks sold for each album
-- 8. Query to find the names of tracks that have a unit price higher than the average unit price of all tracks
-- 9. Query to find the names of employees who earn more than the average salary of their department
-- 10. Find the names of customers along with the titles of albums they have purchased
