erDiagram
    BOOK }|--|| CATEGORY : "belongs to"
    BOOK ||--o{ LOAN : "involved in"
    MEMBER ||--o{ LOAN : "makes"
    STAFF ||--o{ LOAN : "manages"
    PUBLISHER ||--o{ BOOK : "publishes"
    BOOK ||--o{ BOOKAUTHOR : "written by"
    BOOKAUTHOR }o--|| AUTHOR : "written by"

    BOOK {
        string ISBN PK
        string title
        date publishDate
        int copies
        int publisherID FK
        int categoryID FK
    }

    BOOKAUTHOR {
        int bookID PK, FK
        int authorID PK, FK
    }

    AUTHOR {
        int authorID PK
        string name
        string nationality
        date birthDate
    }

    MEMBER {
        int memberID PK
        string name
        string email
        string address
        date joinDate
    }

    LOAN {
        int loanID PK
        date borrowDate
        date dueDate
        date returnDate
        string status
        int staffID FK
        int memberID FK
        int bookID FK
    }

    CATEGORY {
        int categoryID PK
        string name
        string description
    }

    PUBLISHER {
        int publisherID PK
        string name
        string address
        string contact
    }

    STAFF {
        int staffID PK
        string name
        string position
        date hireDate
        string contact
    }